# Configuración de cámaras
cameras:
  2:
    # input_video: "rtsp://admin:Perfumeriasunidas1!@192.168.0.102:554/cam/realmonitor?channel=2&subtype=0"
    input_video: "camera_2.mp4"
    output_video: "camera_2_processed.mp4"
    camera_sn: "AD0B109PAZEC6A7-2"
    polygons:
      - [1, [[150,181],[719,120],[656,569],[790,723],[754,979],[900,1169],[646,1271],[502,1075],[508,788],[410,635],[164,687]]]
      - [2, [[719,120],[1034,120],[933,542],[1044,646],[981,906],[1140,1073],[900,1169],[754,979],[790,723],[656,569]]]
      - [3, [[1034,120],[1369,137],[1271,464],[1423,573],[1340,779],[1488,913],[1140,1073],[981,906],[1044,646],[933,542]]]
      - [4, [[1369,137],[1611,166],[1513,412],[1663,519],[1586,696],[1721,804],[1488,913],[1340,779],[1423,573],[1271,464]]]
      - [5, [[1611,166],[1792,191],[1822,425],[1888,471],[1822,612],[1930,692],[1721,804],[1586,696],[1663,519],[1513,412]]]
  3:
    # input_video: "rtsp://admin:Perfumeriasunidas1!@192.168.0.102:554/cam/realmonitor?channel=3&subtype=0"
    input_video: "camera_3_video.mp4"
    output_video: "camera_3_processed.mp4"
    camera_sn: "AD0B109PAZEC6A7-3"
    polygons:
      - [6, [[43,104],[462,60],[408,637],[473,806],[83,888],[75,685]]]
      - [7, [[494,62],[1021,70],[915,475],[1040,598],[963,848],[1056,961],[794,1036],[721,911],[767,629],[677,500],[452,525]]]
      - [8, [[1021,70],[1290,95],[1169,452],[1267,571],[1169,810],[1240,900],[1056,961],[963,848],[1040,598],[915,475]]]
      - [9, [[1290,95],[1621,143],[1492,431],[1601,533],[1498,729],[1588,806],[1240,900],[1169,810],[1267,571],[1169,452]]]
      - [10, [[604,1430],[614,1190],[1713,821],[1884,1019],[1849,1223],[1505,1430]]]
  5:
    # input_video: "rtsp://admin:Perfumeriasunidas1!@192.168.0.102:554/cam/realmonitor?channel=5&subtype=0"
    input_video: "camera_5_video.mp4"
    output_video: "camera_5_processed.mp4"
    camera_sn: "AD0B109PAZEC6A7-5"
    polygons:
      - [11, [[1632,10],[1751,100],[1615,396],[1423,379],[1338,594],[1154,600],[1036,352],[1194,352],[1252,164],[1444,170],[1505,8]]]
      - [12, [[1751,100],[2057,354],[1834,717],[1676,729],[1542,963],[1321,996],[1154,600],[1338,594],[1423,379],[1615,396]]]
      - [13, [[2057,354],[2414,737],[2414,737],[2047,1194],[1974,1217],[1892,1086],[1736,1104],[1674,1173],[1444,1232],[1321,996],[1542,963],[1676,729],[1834,717]]]
      - [14, [[821,1432],[1392,1428],[988,416],[631,435]]]
  6:
    # input_video: "rtsp://admin:Perfumeriasunidas1!@192.168.0.102:554/cam/realmonitor?channel=6&subtype=0"
    input_video: "camera_6_video.mp4"
    output_video: "camera_6_processed.mp4"
    camera_sn: "AD0B109PAZEC6A7-6"
    polygons:
       - [15, [[858,210],[1252,173],[1275,677],[1344,821],[1440,1013],[950,1084],[925,727]]]
       - [16, [[1252,173],[1615,158],[1607,642],[1694,765],[1344,821],[1275,677]]]
  7:
    # input_video: "rtsp://admin:Perfumeriasunidas1!@192.168.0.102:554/cam/realmonitor?channel=7&subtype=0"
    input_video: "test_ch7.mp4"
    output_video: "camera_7_processed.mp4"
    camera_sn: "AD0B109PAZEC6A7-7"
    save_data: "datos/cam7"
    polygons:
      - [17 ,[[933,133],[1803,306],[1824,421],[1586,1161],[965,965],[865,727]]]