processing:
  segmentation_interval_idle: 200    # Aumentado (antes 100)
  segmentation_interval_active: 30   # Aumentado (antes 10)
  activity_cooldown_frames: 200
  detection_skip_idle: 5             # Aumentado (antes 3)

# Configuración de cámaras
cameras:
  1:
    use_rtsp: false  # true = stream RTSP, false = archivo MP4
    input_video: "video/video1.mp4"
    #input_video: "rtsp://admin:Facil.12@192.168.1.3:554/Streaming/Channels/101"
    output_video: "video/camera_1_processed.mp4"
    camera_sn: "DS-2SE3C204MWG-E/1220240711AAWRFH2517200"
    save_video: true  # true = guarda video procesado, false = solo procesa
    save_data: "data/camera_1"
    # Para videos MP4 (solo si use_rtsp=false)
    start_video: 0
    end_video: 44
    # Para streams RTSP (solo si use_rtsp=true y save_video=true)
    time_save_rtsp: 120  # segundos de grabación
    polygons:
      - [1,[[70,695],[204,1066],[561,1069],[1493,501],[1918,672],[1918,323],[1249,62],[12,300]]]
    input_homography: [[1889,454], [1122,256], [120,1070], [1441,631], [1893,780]]
    output_homography: [[837,72], [324,73], [339,692], [575,363], [758,390]]
    
  2:
    use_rtsp: true
    input_video: "rtsp://admin:Facil.12@192.168.1.64:554/Streaming/Channels/101"
    output_video: "video/camera_2_processed.mp4"
    save_video: false 
    camera_sn: "DS-2SE3C204MWG-E/1220240711AAWRFH2517210"
    save_data: "data/camera_2"
    start_video: 0
    end_video: 30
    time_save_rtsp: 60
    polygons:
      - [2,[[795,1074],[1452,1067],[1518,273],[1494,168],[1016,56],[856,100],[711,46],[148,261],[168,339],[253,469],[511,783]]]  
    input_homography: [[1788, 1070],[1740, 534],[1203, 330],[390, 471],[735, 1070]]
    output_homography: [[171, 437],[351, 674],[808, 648],[851, 202],[295, 90]]

  3:
    use_rtsp: true
    input_video: "rtsp://admin:Facil.12@192.168.1.2:554/Streaming/Channels/101"
    output_video: "video/camera_3_processed.mp4"
    save_video: false 
    camera_sn: "DS-2SE3C204MWG-E/1220240710AAWRFH2517216"
    save_data: "data/camera_3"
    start_video: 0
    end_video: 30
    time_save_rtsp: 60
    polygons:
      - [3, [[1916,773],[1749,933],[1649,941],[878,742],[684,750],[570,792],[143,680],[897,426],[1421,495],[1918,625]]]
    input_homography: [[710,760], [1669,1053], [1902,883], [1900,669], [700,414], [18,690], [18,776], [441,880]]
    output_homography: [[344,187], [11,303], [149,676], [433,763], [1011,568], [487,12], [394,5], [277,77]]