site_name: torch2trt
theme:
    name: "material"
    palette:
        primary: green
        secondary: light green

repo_url: https://github.com/NVIDIA-AI-IOT/torch2trt

plugins:
  - search
  
use_directory_urls: False

edit_uri: blob/master/docs
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Usage:
      - Basic Usage: usage/basic_usage.md
      - Reduced Precision: usage/reduced_precision.md
      - Custom Converter: usage/custom_converter.md
  - Converters: converters.md
  - Benchmarks: 
      - Jetson Nano: benchmarks/jetson_nano.md
      - Jetson Xavier: benchmarks/jetson_xavier.md
  - Contributing: CONTRIBUTING.md
  - See Also: see_also.md

extra_css:
    - css/version-select.css
extra_javascript:
    - js/version-select.js
    
google_analytics:
    - UA-135919510-3
    - auto
    
 
# Configuración de cámaras
cameras:
  1:
    # input_video: "video/video_camara1_0_4__22.mp4"
    input_video: "rtsp://admin:Facil.12@192.168.1.2:554/Streaming/Channels/101"
    output_video: "video/camera_1_processed.mp4"
    camera_sn: "DS-7104NI-Q1-1"
    save_video: false 
    save_data: "data/camera_1"
    polygons:
      - [3, [[1862,767],[1443,633],[794,1077],[123,1072],[3,711],[4,517],[1122,256],[1893,450],[1860,534],[1873,611],[1855,689]]]
    input_homography: [[1889,454], [1122,256], [120,1070], [1441,631], [1893,780]]
    output_homography: [[837,72], [324,73], [339,692], [575,363], [758,390]]
    
  2:
    # input_video: "video/video_camara2_0_51.mp4"
    input_video: "rtsp://admin:Facil.12@192.168.1.64:554/Streaming/Channels/101"
    output_video: "video/camera_2_processed.mp4"
    save_video: false 
    camera_sn: "DS-7104NI-Q1-2"
    save_data: "data/camera_2"
    polygons:
      - [2, [[1740,533],[1788,1075],[741,1074],[433,591],[400,480],[536,442],[1008,365],[1061,398],[1128,389],[1214,431],[1369,397]]]  
    input_homography: [[1788, 1070],[1740, 534],[1203, 330],[390, 471],[735, 1070]]
    output_homography: [[171, 437],[351, 674],[808, 648],[851, 202],[295, 90]]

  3:
    # input_video: "video/video_camara3_0_100.mp4"
    input_video: "rtsp://admin:Facil.12@192.168.1.47:554/Streaming/Channels/101"
    output_video: "video/camera_3_processed.mp4"
    save_video: false 
    camera_sn: "DS-7104NI-Q1-3"
    save_data: "data/camera_3"
    polygons:
      - [1, [[20, 691], [18, 779], [414, 881], [709, 759],[1675, 1060], [1902, 890], [1902, 667], [704, 416]]]
    input_homography: [[710,760], [1669,1053], [1902,883], [1900,669], [700,414], [18,690], [18,776], [441,880]]
    output_homography: [[344,187], [11,303], [149,676], [433,763], [1011,568], [487,12], [394,5], [277,77]]